@EsportsPortal.WebApi_HostAddress = https://localhost:7070

GET {{EsportsPortal.WebApi_HostAddress}}/api/users/info
Accept: application/json
Authorization: Bearer CfDJ8DTpHG8efNBAjK3ExMGPKqjpgE8nvzo1oEBqgN1FS2ty320Dh4ib-R0SqVidwG20w1_pirhvqyzieTKeDeJZu0iXdtYfnzcVb-BeL-ozqc13HiEEyQJXIi3Oir7P7Imgc1EHMwstJa4nuHbdiPf_wUqRrqwDZig_-BE7v4r5QODIb044ZnW3qu7kLq2g3GsXT1oHY-YOnHg-MQ1ou5OXUPSPG6Bn_DKkQEZ5ElYYTx4-VMufJTkifx68wngOHcp7LoQqevmRmL13HX2y6jdKN7ZtTGJ4qg500Oz-k4mgoArplj-2CgZunyFVNE6IyxAMBAhwgbM1w3b8Vt-WB9V4uutKiVvmktucJHv_Qc_MAORkn_bhBMx55EkxChqHxaInc7kA27rMqFgrIqABAJHjiEb27NUV2VoGiysSukMZUfq1EQt0QBYXJvTl-deGEE4xaEpxo2G518-JCdGN-wx2A1g00hNI4aBsJ_yOd6KNfzPEEdv3sz7CKKoiK847uVwgdhual0TNd2HLDjkophih0fW8ISCGBVnTgszqmViMwax1U1r_Xati30BE3oU1Zp941un_aw0cOy_csAeVTNaNUMNntYjYV110yYicHHFo8HSqkGierIf1af2inqrSuPDvSPpW0R-SSfbkN1k8ScyQS0NF_AjTQ4XujB1x-zxQi2Tn5ulsPM2q0mjSZm_3f0N9StdwBOlgX-k55B-F2_wVdpc

###
